export const LOAD_INITIAL_STATE = "LOAD_INITIAL_STATE"
export const ADD_NEW_TASK = "ADD_NEW_TASK"
export const HANDLE_NEW_TASK_CHANGE = "HANDLE_NEW_TASK_CHANGE"
export const CHANGE_CARD_CATEGORY = "CHANGE_CARD_CATEGORY"